---
title: matt sullivan
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'I am a ux/product designer with a background in human centered design.
  designs with data & user research most of the time, intuition & experience the rest
  of the time. '
baseurl: 
url: 
twitter_username: mjsxi
github_username: mjsxi
permalink: "/projects/:title.html"
markdown: kramdown
excerpt_separator: "<!--more-->"
gems:
- jekyll-feed
- jekyll-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
